server:
  port: 8080
spring:
  mail:
    host: smtp.gmail.com
    port: 587
#   username: 구글 계정
    #password: 구글 계정 앱 비밀번호
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  mvc:
    view:
      prefix: classpath:/templates/
      suffix: .html
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://aniwell.crg6u0s2maw3.ap-northeast-2.rds.amazonaws.com:3306/aniwell?serverTimezone=Asia/Seoul
    username: HES
    password: aniwell1234
mybatis:
  type-aliases-package: com.example.RSW.vo
  mapper-locations: classpath:/mappers/**/*.xml

custom:
  siteName: aniwell
  siteMainUri: http://localhost:8080
  emailFrom: no-reply@localhost
  emailFromName: aniwell

kakao:
  rest-api-key: "79f2a3a73883a82595a2202187f96cc5"    # 로그인
  javascript-key: "dfd275f49b78960a0458d6f6294cbde2"
  client-secret: "61Ng1JnIKgkQRXgxaJOpY9wo4gffwvn2"
  redirect-uri: "http://localhost:8080/usr/member/kakao"  #로그인 redirect URI

cloudinary:
    cloud_name: dfiqktimk
    api_key: 145284189636895
    api_secret: 4TS23PL5HMWPolljcIRqitpWwU0
